### ISSUE TITLE
ru clasters

### ISSUE THREAD

**Issue by sem174** [AlekiCreative/WorldOfTanks_CIS#1]
Good afternoon
on a local machine (Open Server) I tried to run your project.
But since I have an account on the RU cluster, I replaced worldoftanks.eu with  worldoftanks.ru  in all the project files.
It even partially worked.But then fail.
![2021-12-06_17-51-25](https://user-images.githubusercontent.com/8233588/144868250-a1be9fd0-8f77-4b11-a133-0fb7469eef98.png)
![2021-12-06_17-52-32](https://user-images.githubusercontent.com/8233588/144868266-7cea6e9b-dd08-4cbe-92c3-52d5696184fc.png)
`localhost: 127.0.0.1 [06/Dec/2021:17:50:20 +0300] "GET / HTTP/1.1" 200 2126 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
localhost: 127.0.0.1 [06/Dec/2021:17:50:25 +0300] "GET / HTTP/1.1" 200 2126 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
localhost: 127.0.0.1 [06/Dec/2021:17:50:28 +0300] "GET /config/auth.php? HTTP/1.1" 301 - "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
default: 127.0.0.1 [06/Dec/2021:17:50:40 +0300] "-" 408 - "-" "-"
default: 127.0.0.1 [06/Dec/2021:17:50:40 +0300] "-" 408 - "-" "-"
localhost: 127.0.0.1 [06/Dec/2021:17:51:31 +0300] "GET /ManagmentSystem/WorldOfTanks_CIS/config/auth.php?&status=ok&access_token=*****9632ab627de5cb8b4c470a0f7236cc2b202&nickname=******&account_id=*****5352&expires_at=1638802524 HTTP/1.1" 404 1269 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
localhost: 127.0.0.1 [06/Dec/2021:17:58:23 +0300] "GET / HTTP/1.1" 200 2126 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
localhost: 127.0.0.1 [06/Dec/2021:17:58:25 +0300] "GET / HTTP/1.1" 200 2126 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
localhost: 127.0.0.1 [06/Dec/2021:17:58:26 +0300] "GET /config/auth.php? HTTP/1.1" 301 - "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
localhost: 127.0.0.1 [06/Dec/2021:17:58:30 +0300] "GET /ManagmentSystem/WorldOfTanks_CIS/config/auth.php?&status=ok&access_token=*****d0a096c5850442ebdf23f647259b6d19065&nickname=*****&account_id=******5352&expires_at=1638803002 HTTP/1.1" 404 1269 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
localhost: 127.0.0.1 [06/Dec/2021:17:58:35 +0300] "GET /ManagmentSystem/WorldOfTanks_CIS/config/auth.php?&status=ok&access_token=*****d0a096c5850442ebdf23f647259b6d19065&nickname=******&account_id=******5352&expires_at=1638803002 HTTP/1.1" 404 1269 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.2.773 Yowser/2.5 Safari/537.36"
default: 127.0.0.1 [06/Dec/2021:17:58:43 +0300] "-" 408 - "-" "-"
default: 127.0.0.1 [06/Dec/2021:17:58:43 +0300] "-" 408 - "-" "-"`

**Comment by AlekiCreative** [comment]
Hello,
**I apologize for the inconvenience, but unfortunately I temporarily suspended the project.
Developments resumed in the coming months.**

- They point out that the MSQL database created, which is updated via a [java server](https://github.com/AlekiCreative/WorldOfTanks_CIS-server) , is required for proper operation. (My mistake I wrote the information page)

- Unfortunately, the correct installation procedure cannot be pleased as it has not yet been developed and tested

- Since I developed the project on the EU server, it is possible that somewhere the part of the code will be specific only to the EU. (Compatibility for other servers is planned)

**They recommend waiting for a "functional prototype"**
During the year beginning in 2022, I will redesign the java server and start working on the installation server

_I apologize for the wrong incorrect translation_

**Comment by sem174** [comment]
Everything I could achieve in the end
![2021-12-06_22-41-00](https://user-images.githubusercontent.com/8233588/144911793-e69f8fb7-b43c-43c9-a3ea-650a9abe30d1.png)

**Comment by AlekiCreative** [comment]
Oh, I'm sorry, I put a block for other clans in the code.

**There is an option in the system to block clans other than yours.** 

config\get_data.php -> line 13 

> $allowed_clan = explode(",", DB_CONN("allowed_clans","option_name","cis_ini")[2]);

**Comment by sem174** [comment]
Nothing changes, just a bunch of errors in php, when going directly to /clan-personal.php or something like that.

**Comment by sem174** [comment]
![2021-12-06_23-12-55](https://user-images.githubusercontent.com/8233588/144915649-94947fa9-29d7-4b2d-8102-6cc25edd8683.png)

**Comment by AlekiCreative** [comment]
So I'm so sorry, I'll try to locate the bugs and fix them in the coming days

**They estimate the functional prototype at the end of Q1 2022**

**Comment by sem174** [comment]
ok
